### ISSUE TITLE
Bazel vs. wasme builds

### ISSUE THREAD

**Issue by anirudhSK** [dyn-tracing/snicket_compiler#49]
Right now, the README.md has both a Bazel as well as a wasme build step. But it's unclear why both of them are needed. Further, the Bazel step can take a significant amount of time.

**Comment by anirudhSK** [comment]
The Bazel build produces a .wasm file, which the wasme loads using the "precompiled" mode: https://docs.solo.io/web-assembly-hub/latest/reference/cli/wasme_build_precompiled/

Additionally, it seems like the long build times are a known problem and Bazel builds might help with this: https://github.com/solo-io/wasm/issues/97

**Comment by anirudhSK** [comment]
wasme build cpp takes ~15 minutes on the first build, while Bazel build is a bit faster (< 10 minutes). Both are still slow, but it doesn't look like there's an easy fix.

Subsequent builds do seem to reduce build times with bazel build, but not much with wasme build cpp. I think this is because wasme build cpp launches a new docker container with bazel for every run, so any previous build results aren't reused.

**Comment by fruffy** [comment]
We switched to Rust. So this issue does no longer apply.
